### ISSUE TITLE
Feature Request: Private Repo Support

### ISSUE THREAD

**Issue by plashal** [r24y/github-issues#39]
> This is a feature request, not a bug report.

It would be nice to have support for private repositories. I see in the past (as far back as last year), there's some discussion for private repositories. not sure if there's been any head

I'll see if i can make some time and help out the cause. 
but i'm sure you are, as am i, working your tail off with not much free time for new projects. 

my initial take, when looking into this; i think we got start with private apm requests?!.

- https://github.com/atom/atom/blob/master/docs/apm-rest-api.md
- https://developer.github.com/early-access/integrations/authentication/
- https://atom.io/docs/api/v1.15.0/PackageManager#instance-getApmPath
- https://discuss.atom.io/t/private-apm-registries/16592

anyway, I'll see what i can do.

**Comment by r24y** [comment]
Hi @plashal, thanks for checking in. I've actually spent some effort over the past few days starting to clean this up and I look forward to pushing a new version within the next 7 days.

Right now I'm planning on using GitHub's "personal tokens" feature for authentication, but I'll investigate those links you've sent in further detail once I've got the next version out since I know folks have been itching for it. Thank you for the info 😃 

I'm going to close this issue in favor of identical issue #38.
